<?php
    //Token Constant
    define('TOKEN','YOUR_TOKEN');

    //save data in file.txt 
    $data = json_decode(file_get_contents('php://input'), TRUE);

    file_put_contents('file.txt', '$data: '.print_r($data, 1)."\n", FILE_APPEND);

    $data = $data['message'] ? $data['message'] : $data['callback_query'];

    $message_in = mb_strtolower(($data['text'] ? $data['text'] : $data['data']), 'utf-8');

    $user_id = $data['chat']['id'];

    $facebookPage= file_get_contents("https://graph.facebook.com/v12.0/YOUR_PAGE_ID/feed?access_token=YOUR_TOKEN");

    $array = json_decode($facebookPage, true);

    if($message_in){

        // if($message_in && $data['message']['chat']['id'] == '1228669226' ){
           
        // }


        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
   
        # TEST GROUP
        // $method = 'sendMessage';
        // $send_data = [
        //     'text' => $message_in
        // ];
        // $send_data['chat_id'] = '-1001731563531';
        // $res = sendTelegram($method, $send_data);

        # TEST CHANNEL
        // $method = 'sendMessage';
        // $send_data = [
        //     'text' => $message_in
        // ];
        // $send_data['chat_id'] = '-1001167376883';
        // $res = sendTelegram($method, $send_data);

        // $method = 'sendMessage';
        // $send_data = [
        //     'text' => $message_in
        // ];
        // $send_data['chat_id'] = '805533361';
        // $res = sendTelegram($method, $send_data);


        $method = 'sendPhoto';
        $send_data = [
            'photo' => 'https://www.facebook.com/images/fb_icon_325x325.png',
            'caption' => 'Text caption'
        ];
        $send_data['chat_id'] = $user_id;
        $res = sendTelegram($method, $send_data, urlencode($message_in));

        
        

        
        // $method = 'sendPhoto';
        // $send_data = [
        //     'photo' => 'https://cdn.pixabay.com/photo/2017/01/03/02/07/vine-1948358__340.png'
        // ];
        // $send_data['chat_id'] = '-1001167376883';
        // $res = sendTelegram($method, $send_data);

        
        // $method = 'sendMessage';
        // $send_data = [
        //     'text' => 'Ushbu Maxsulot'
        // ];
        // $send_data['chat_id'] = '-1001167376883';
        // $res = sendTelegram($method, $send_data);

        
        // $method = 'sendPhoto';
        // $send_data = [
        //     'photo' => 'https://cdn.pixabay.com/photo/2017/01/03/02/07/vine-1948358__340.png'
        // ];
        // $send_data['chat_id'] = '-1001731563531';
        // $res = sendTelegram($method, $send_data);

        
        // $method = 'sendMessage';
        // $send_data = [
        //     'text' => 'Ushbu Maxsulot'
        // ];
        // $send_data['chat_id'] = '-1001731563531';
        // $res = sendTelegram($method, $send_data);
         
     } if(!empty($facebookPage)){
        foreach($array['data'] as $key => $value){
            if($key == 0){
                   
                    $method = 'sendMessage';
                    $send_data = [
                    'text' => $value['message']."\n\n". "<b>"."@hby_cl"."</b>",
                    'parse_mode' => 'HTML'
                    
                    
                    ];
                    $send_data['chat_id'] = $user_id;
                    $res = sendTelegram($method, $send_data,urlencode($message_in));
                    
            }
        }
        
        // You can send a message to a Channel, Group, or Personal Account
        // Send to Group
        // foreach($array['data'] as $key => $value){
        //     if($key == 0){
                 
        //             $method = 'sendMessage';
        //             $send_data = [
        //             'text' => $value['message']
                    
        //             ];
        //             $send_data['chat_id'] = GROUP_ID;
        //             $res = sendTelegram($method, $send_data);
                    
        //     }
        // }

        // Send to Channel
        // foreach($array['data'] as $key => $value){
        //     if($key == 0){
                   
        //             $method = 'sendMessage';
        //             $send_data = [
        //             'text' => $value['message']
                    
        //             ];
        //             $send_data['chat_id'] = CHANNEL_ID;
        //             $res = sendTelegram($method, $send_data);
                    
        //     }
        // } 

        // Send to Personal Account
        // foreach($array['data'] as $key => $value){
        //     if($key == 0){
                    
        //             $method = 'sendMessage';
        //             $send_data = [
        //             'text' => $value['message']
                    
        //             ];
        //             $send_data['chat_id'] = TELEGRAM_USER_ID;
        //             $res = sendTelegram($method, $send_data);
                    
        //     }
        // }
            
        
    }
    // Function to send messages to Telegram Bot API
    // When the first API POST REQUEST to TELEGRAM BOT API done
    // execute the second POST request to Facebook Graph API to post a message to your page's feed
    function sendTelegram($method, $data, $fbpost, $headers = []){
         
        $curl = curl_init();
        curl_setopt_array($curl, [
            CURLOPT_POST => 1,
            CURLOPT_HEADER => 0,
            CURLOPT_RETURNTRANSFER => 1,
            CURLOPT_URL => 'https://api.telegram.org/bot'. TOKEN .'/'.$method,
            CURLOPT_POSTFIELDS => json_encode($data),
            CURLOPT_HTTPHEADER => array_merge(array("Content-Type: application/json"), $headers)
        ]);

        $result = curl_exec($curl);
        $result = json_decode($result, true);

        // check the first request is sent successfully
        if($result['ok'] ='111')
        {
        //    echo "works";
        //    print_r($result);
            // if the result dictates that you make another request, update the url
            curl_setopt($curl, CURLOPT_URL, 'https://graph.facebook.com/v12.0/YOUR_PAGE_ID/feed?message='.$fbpost.'&access_token=YOUR_TOKEN');

            // execute the second request
            $result2 = curl_exec($curl);

            // do something with $result2
        }
        curl_close($curl);
        
        return(json_decode($result, 1)? json_decode($result, 1) : $result);        

    }
       
?>


 